name: crfpe_mobile
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  readmore: ^3.0.0
  flutter_svg: ^1.0.3
  table_calendar: ^3.0.0
  http: ^1.2.2
  shared_preferences: ^2.0.6  # Ajoutez cette ligne pour utiliser flutter_svg
  dio: ^5.5.0+1
  firebase_core: ^3.2.0
  firebase_auth: ^5.1.2
  google_sign_in: ^6.2.1
  google_fonts: 6.2.1
  cookie_jar: ^3.0.1
  dio_cookie_manager: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.9.2
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.svg"  

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.svg  # Ajoutez le logo SVG ici
    - assets/images/bg_liquid.png
    - assets/images/avatar.png
